### ISSUE TITLE
Replace custom certificate serialization, rich notification validation & decryption code by SDK methods

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/aspnetcore-webhooks-sample#170]
The SDK recently added support for rich notifications to make things simpler for consumers and avoid code duplication.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1053

The custom code should be stripped to make use of those new capabilities:
- https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/main/src/GraphWebhooks-Core/TokenValidator.cs
- https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/main/src/GraphWebhooks-Core/Decryptor.cs
- https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/e3cac2f0db822fd4c3ab954d6ad116afab818e75/src/GraphWebhooks-Core/KeyVaultManager.cs#L55

**Comment by baywet** [comment]
Thanks for taking this on. Should we wait before merge 192 for this to be fixed?

**Comment by jasonjoh** [comment]
We can but we don't have to - I implemented the token validation as an [extension on ChangeNotificationCollection](https://github.com/microsoftgraph/aspnetcore-webhooks-sample/pull/192/files#diff-c59612c02d581ed8e84ee7039700d988a126c16fb6126673e179ab831e6cb134) so it should be fairly easy to swap it out.

**Comment by baywet** [comment]
Should we open another issue here to keep tracks of updating when the v2 issue is fixed in the sdk?
