### ISSUE TITLE
IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user

### ISSUE THREAD

**Issue by AABhatt** [microsoftgraph/aspnetcore-webhooks-sample#202]
I created web api to subscribe and listen for graph notification. Once I got notification for mail inbox then I try to call graph api using user delegated permission. I used this code but at await request.GetAsync() it throws me an exception. IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user and inner exception message like No 'account or login hint was passed to the AcquireTokenSilent call'. I have given all permission. Need help.

**Comment by AABhatt** [comment]
It looks very complex to handle in Rest Api as it needs persistent identity for all users who subscribed but during api restart it looks not good solution. So I am trying with application level permission to get further data from graph api after notification received.

**Comment by jasonjoh** [comment]
Yes, this is a challenge for a notification endpoint. We handle it in this sample by having the user sign in to create the subscription. By doing so, the MSAL token cache gets created for that particular user in memory. When the notification comes in, we use the tenant and user ID that we store in our subscription store to create a user claim principal, which allows Microsoft.Identity.Web to locate the correct token cache and get a token for the user.

https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/7d40ee12fd7964c79fbf94fe268d73ca77fda717/src/GraphWebhooks/Controllers/ListenController.cs#L183-L190

Of course in-memory caches are brittle, so implementing a persistent cache would be recommended for a production scenario.
