### ISSUE TITLE
Feature Request: Automatic Subscription renewal 

### ISSUE THREAD

**Issue by thaxy** [microsoftgraph/aspnetcore-webhooks-sample#205]
Scenario: We want to deploy a webhook endpoint that basically runs 24/7 and listens for mail events in a specific 'service account' email folder.
The docs are clear about how a subscription can be renewed.
It would be nice to have a good pattern in this repo on how this could be achieved.

My first guess is to use [a timed background task with hosted services](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio
).

Any other suggestions?

**Comment by jasonjoh** [comment]
A hosted service could possibly work, but authentication would be a challenge. For the subscriptions created as a user, any background task isn't going to be running in that user's context, or have access to that user's access tokens.

Also, the current implementation for storing the subscriptions doesn't directly support a way to get subscriptions out without knowing their IDs.

**Comment by jasonjoh** [comment]
Lifecycle notifications look like a good solution for this. See https://learn.microsoft.com/en-us/graph/webhooks-lifecycle?tabs=http for details. Need to add a handler for these notifications and use them to renew the subscription.
