### ISSUE TITLE
deserializtion of notifications fails because no deserialization provider is registered

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/aspnetcore-webhooks-sample#335]
here 
https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/9be538d386f941ecfa675c902cb596ae42d7a8ea/src/GraphWebhooks/Controllers/ListenController.cs#L76
and there
https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/9be538d386f941ecfa675c902cb596ae42d7a8ea/src/GraphWebhooks/Controllers/LifecycleController.cs#L54

The following line needs to be added
```csharp
ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
```

**Comment by jasonjoh** [comment]
This failure doesn't happen in this sample because there is an instance of `GraphServiceClient`, which already registers the JSON provider for you. However, will add the line (even though it's redundant) so folks that copy code from this sample are covered in all cases.
