### ISSUE TITLE
SDK entities in example not available in Microsoft Graph SDK

### ISSUE THREAD

**Issue by jorgeolive** [microsoftgraph/aspnetcore-webhooks-sample#36]
Hi,

As of Microsoft.Graph v 3.5.0, I cannot find objects such as "ChangeNotificationCollection".  I've noticed that you're using **Microsoft.Graph.Beta** library. 

Will these models be eventually included in the SDK?

Thanks
Jorge.

**Comment by baywet** [comment]
Yes the goal is to provide these entities in the v1 SDK and as you mentioned they are only available in beta for now.
We're waiting to get more feedback from people using the beta version before promoting things to v1
