### ISSUE TITLE
Not work on Mac OS

### ISSUE THREAD

**Issue by nguyentoantuit** [microsoftgraph/aspnetcore-webhooks-sample#8]
I implement a notification change on sent mailbox. So whenever user send a message, I would like receive a notification. Everything work fine if I test it on Windows machine or on outlook web app, however it doesn't work if I test it on Mac OS. Do you have any idea why it could happen?

My testing Mac OS version: macOS Sierra version 10.12.6
Outlook version: Outlook for Mac, version 16.29 (19090802)

**Comment by baywet** [comment]
Hey @nguyentoantuit 
Thanks for reaching out and sorry for the delay in the reply.

Do you mean that the sample does not work when the sample is running on a MacOS machine? or do you mean that it does not work when sending/receiving emails from the MacOS client?
