### ISSUE TITLE
Graph Beta API Rejects Multiple Subscriptions (Issue Confirmed With MS Support)

### ISSUE THREAD

**Issue by edjames99** [microsoftgraph/aspnetcore-webhooks-sample#92]
Hi,
I'm trying to modify the test application found at:
https://docs.microsoft.com/en-us/samples/microsoftgraph/aspnetcore-webhooks-sample/microsoft-graph-change-notifications-sample-for-aspnet-core/

I'm trying to have multiple simultaneous subscriptions for presence as I believe that a single subscription can have up to 650 users and we have clients with potentially thousands of users for which we need the presence. I made the following very simple code change where I added in a second new subscription to the CreateSubscription function and I get an error saying a subscription already exists and that one has to be deleted before a new one can be created.
This is the modified function:

        private async Task<Subscription> CreateSubscription(string userId, string tenantId, string clientState, GraphServiceClient graphClient)
        {
            string encryptionCertificate = subscriptionOptions.Value.IncludeResourceData ? await keyVaultManager.GetEncryptionCertificate().ConfigureAwait(false) : null;
            string encryptionCertificateId = subscriptionOptions.Value.IncludeResourceData ? await keyVaultManager.GetEncryptionCertificateId().ConfigureAwait(false) : null;

            var newSubscription = await graphClient.Subscriptions.Request().AddAsync(new Subscription
            {
                Resource = "/communications/presences?$filter=id in ('0d90bdbc-2dcc-4d8e-8d1f-648330acc24b')", //subscriptionOptions.Value.Resource,
                ChangeType = subscriptionOptions.Value.ChangeType,
                NotificationUrl = subscriptionOptions.Value.NotificationUrl,
                ClientState = clientState,
                ExpirationDateTime = DateTime.UtcNow + new TimeSpan(0, 0, 0, 60),     // 4230 minutes is the current max lifetime, shorter duration useful for testing
                EncryptionCertificate = encryptionCertificate,
                EncryptionCertificateId = encryptionCertificateId,
                IncludeResourceData = subscriptionOptions.Value.IncludeResourceData
            }) ; 

            // This sample temporarily stores the subscription data, but production apps will likely use some method of persistent storage.
            // This sample stores the client state to validate the subscription, the tenant ID to reuse tokens, and the user ID to filter
            // messages to display by user.
            subscriptionStore.SaveSubscriptionInfo(Guid.Parse(newSubscription.Id),
                newSubscription.ClientState,
                userId,
                tenantId);

            // ** Create a second subscription for the presence of a different Teams user
            var newSubscription2 = await graphClient.Subscriptions.Request().AddAsync(new Subscription
            {
                Resource = "/communications/presences?$filter=id in ('d3ad693e-6edb-4762-af08-d1eab45a5076')", //subscriptionOptions.Value.Resource,
                ChangeType = subscriptionOptions.Value.ChangeType,
                NotificationUrl = subscriptionOptions.Value.NotificationUrl,
                ClientState = clientState,
                ExpirationDateTime = DateTime.UtcNow + new TimeSpan(0, 0, 0, 60),     // 4230 minutes is the current max lifetime, shorter duration useful for testing
                EncryptionCertificate = encryptionCertificate,
                EncryptionCertificateId = encryptionCertificateId,
                IncludeResourceData = subscriptionOptions.Value.IncludeResourceData
            });

            // This sample temporarily stores the subscription data, but production apps will likely use some method of persistent storage.
            // This sample stores the client state to validate the subscription, the tenant ID to reuse tokens, and the user ID to filter
            // messages to display by user.
            subscriptionStore.SaveSubscriptionInfo(Guid.Parse(newSubscription2.Id),
                newSubscription2.ClientState,
                userId,
                tenantId);

            return newSubscription;
        }

I've been talking to MS support (gclark@microsoft.com and djball@microsoft.com) about this and they tried the same thing and got the same error but it did work when the Resource wasn't /communications/presences in both cases so maybe that's the reason ? Note that the full resource string in the case above is different for the two subscriptions even though the resource is /communications/presences in both cases. He said that he thought what I was trying to do should work.

If anything isn't clear then let me know.
Thanks
Ed James

**Comment by baywet** [comment]
Hi @edjames99 
Cloud you share the error message you are getting please?
Also, why don't you use `/communications/presences?$filter=id in ('d3ad693e-6edb-4762-af08-d1eab45a5076','0d90bdbc-2dcc-4d8e-8d1f-648330acc24b')` as the resource ?

**Comment by edjames99** [comment]
Hi, 
As far as I know, a single subscription can handle up to 650 users and we have clients with thousands of users so we will need more than one subscription at once. I've tested multiple users on a single subscription and that works and I was starting with the simplest multiple subscription scenario of two subscriptions each with one user.

The 650 limit I got from the following:
https://developer.microsoft.com/en-us/graph/blogs/get-notified-of-presence-changes-the-microsoft-graph-presence-subscription-api-is-now-available-in-public-preview/

Do you know if 650 is definitely the limit ?

Also, I see the following error:

Error
An error occurred while processing your request.
Operation: Create; Exception: [Status Code: Conflict; Reason: A subscripton already exists. It must be deleted before a another can be made.] Request ID: 46406ec1-e0dd-4514-b7da-195a6df2b833 Date: 2020-11-26T14:15:23

**Comment by baywet** [comment]
Thanks for the additional details.
This is an issue with the service, there's not much we can do in the sample. Please get in touch with support and ask them to escalate to the IC3 team (team in charge of the presence information).
Closing.

**Comment by edjames99** [comment]
Hi, I was talking to Geoff Clark in MS support and he told me to raise it on GitHub as follows:
 
"My recommendation would be report an issue on GitHub for this problem.  The resource is still in Preview and the Product Group should be notified of this issue via GitHub."

So should I go back to them and pass your message on ? 
Also do you know anything about the 650 limit ? Is that correct ?

**Comment by baywet** [comment]
Again, all those questions can be answered by the product group. This sample is built and maintained by the developer experience group which is cross-products.

**Comment by edjames99** [comment]
OK, so is IC3 the product group ?

**Comment by baywet** [comment]
yes

**Comment by edjames99** [comment]
OK thanks for your help.
