### ISSUE TITLE
Activity Not Defined in the ChangeNotification Class (Issue Confirmed with MS Support)

### ISSUE THREAD

**Issue by edjames99** [microsoftgraph/aspnetcore-webhooks-sample#93]
Hello,
I'm using the following test app to retrieve presence:
https://docs.microsoft.com/en-us/samples/microsoftgraph/aspnetcore-webhooks-sample/microsoft-graph-change-notifications-sample-for-aspnet-core/

In the following function which receives the webhooks callbacks. It initially does the following code to retrieve the plain text notifications:

        // The notificationUrl endpoint that's registered with the webhook subscription.
        [HttpPost]
        [AuthorizeForScopes(ScopeKeySection = "SubscriptionSettings:Scope")]
        public async Task<IActionResult> Listen([FromQuery]string validationToken = null)
        {
        
            if (string.IsNullOrEmpty(validationToken))
            {
                try
                {

                    // Parse the received notifications.
                    var plainNotifications = new Dictionary<string, ChangeNotification>();
                    var options = new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    };
                    options.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
                    var collection = await JsonSerializer.DeserializeAsync<ChangeNotificationCollection>(Request.Body, options);
                    foreach (var notification in collection.Value.Where(x => x.EncryptedContent == null))
                    {
                        SubscriptionStore subscription = subscriptionStore.GetSubscriptionInfo(notification.SubscriptionId.Value);

                        // Verify the current client state matches the one that was sent.
                        if (notification.ClientState == subscription.ClientState)
                        {
                            // Just keep the latest notification for each resource. No point pulling data more than once.
                            plainNotifications[notification.Resource] = notification;
                        }
                    }

                    if (plainNotifications.Count > 0)
                    {
                        // Query for the changed messages. 
                        await GetChangedMessagesAsync(plainNotifications.Values);
                    }

The issue is that neither Activity nor Availability are defined in the ChangeNotification class and so the presence updates cannot be retrieved. They are definitely being received as they can be seen on the Ngrok interface.

Note that there is a workaround in that you can do the following (this was provided by MS support gclark@microsoft.com):

                    string l_szReqBody = await new StreamReader(Request.Body).ReadToEndAsync();
                    string l_szDisplay = "";
                    dynamic data = JsonConvert.DeserializeObject(l_szReqBody);

                    // Verify if the request body is not empty and has json data
                    if (!string.IsNullOrEmpty(l_szReqBody))
                    {
                        JObject body = JObject.Parse(l_szReqBody);
                        if (body.ContainsKey("value"))
                        {
                            //JValue resource = (JValue)body["value"][0]["resource"];
                            l_szDisplay = string.Concat("WEB HOOK:" + "ID=" + body["value"][0]["resourceData"]["id"] + 
                                ", Activity=" + body["value"][0]["resourceData"]["activity"] +
                                ", Availability=" + body["value"][0]["resourceData"]["availability"]);
                        }
                    }

Are there any plans to add Activity and Availability to the ChangeNotification class or should I stick with the workaround ?

Thanks
Ed James

**Comment by baywet** [comment]
Hi @edjames99 
Thanks for reaching out. I'm not sure why you need a workaround to access the data? After token validation, symmetric key decryption, signature validation, and payload decryption, the full JSON representation of the data is available in the [decryptedpublisherNotification string](https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/master/src/GraphWebhooks-Core/Controllers/NotificationController.cs#L121)
Just adding `var presence = JsonSerializer.Deserialize<Presence>(decryptedpublisherNotification, options);` after that line will give you the deserialized payload using the types provided by the SDK.

**Comment by edjames99** [comment]
It doesn't get that far as collection.ValidationTokens is null so the decryptedpublisherNotification string isn't populated.

**Comment by baywet** [comment]
Have you set `IncludeResourceData` to `true` in the configuration as well as created the key vault, granted permissions to it for your application, generated the self-signed certificate and updated the keyvault settings in the configuration file?

**Comment by edjames99** [comment]
Geoff Clark from MS support said I didn't need IncludeResourceData to be true so I haven't created a key vault. I have granted delegate permissions to the app (as you can't get presence with application permissions). Geoff said the issue was that the Microsoft.Graph.ChangeNotification class doesn't contain Activity so it's not available.

**Comment by baywet** [comment]
change notifications do not contain resource data by default. They tell you "something has changed there", you then need to query the information, which you can see being done in [GetChangedMessagesAsync](https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/master/src/GraphWebhooks-Core/Controllers/NotificationController.cs#L158) (might need to be adapted in the case of Presence) or you need to request change notifications to include resource data so it gets delivered with the notification. (only teams presence and teams chat messages support it at this time)

**Comment by edjames99** [comment]
OK thanks, I'll take a look tomorrow. Have you got any code that can request change notifications to include resource data ? How do I do that ?

**Comment by baywet** [comment]
This sample does that, as long as you configure it to do so.
As the question has been answered, I'll close this issue for now.

**Comment by edjames99** [comment]
One more question, if I've already done the Azure registration without creating a key vault can I now go back and create one and re-save the same registration or do I need to do a fresh registration from scratch ?

**Comment by baywet** [comment]
no you can keep your current registration, just go through the steps you haven't been through yet

**Comment by edjames99** [comment]
Thanks for your help, I appreciate it. I wonder if I could pick your brain about the best way forward for our production strength application. What we need ideally is an application which does not require any user input and which can retrieve presence data from potentially thousands of users.
So far I've discovered the following:
1. Presence is only available with delegated permissions and not with application permissions. 
2. Delegated permissions requires a user to log in and in the example ASP.NET applications currently available this means manual user input.
3. A subscription supports 650 users max so we will need multiple simultaneous subscriptions.

When we did the Skype for Business integration we had a trusted application running as a windows service subscribing to presence states of thousands of users but it looks like we can't have presence via application permissions (is there a reason for this ?) so we have to have delegated permissions but we don't want manual user login so we have to find a way of doing the login to MS programmatically.

Do you have any example apps that retrieve presence and log in to MS without manual user input ? How difficult would it be to suppress the manual login in the ASP.NET application ?

Any comments or ideas would be welcome as we're currently not sure on the best way forward.

**Comment by edjames99** [comment]
Hi, I'm trying to set up the Azure Key Vault as described on https://docs.microsoft.com/en-us/samples/microsoftgraph/aspnetcore-webhooks-sample/microsoft-graph-change-notifications-sample-for-aspnet-core/ but when I click through on the link it says 404 site not found. 
Do you have a link to the steps to set up the key vault so I can see the presence coming through ?

**Comment by baywet** [comment]
without user input: this would require the API to support app only, and it doesn't today. You should [upvote this idea](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/39219637-application-permission-for-presence) to help prioritize the work for app only (and also be notified when it comes online).

Key vault: https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/master/KEYVAULT.md

**Comment by edjames99** [comment]
Thanks, I'm trying to add a resource group and it's saying we don't have a subscription yet the rest of the app registration works in the Azure Active Directory. So is the Azure Portal different and so we need a separate subscription to the portal to be able to create this key vault ?

**Comment by baywet** [comment]
you need an active azure subscription yes. It is possible to use the feature (change notifications with resource data) without using the Azure KeyVault by generating and storing the certificate somewhere else/yourself, but this sample doesn't show that.
